-- MySQL Script generated by MySQL Workbench
-- Sun Nov 12 11:03:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema troca_verde
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema troca_verde
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `troca_verde` DEFAULT CHARACTER SET utf8 ;
USE `troca_verde` ;

-- -----------------------------------------------------
-- Table `troca_verde`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(60) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `logradouro` VARCHAR(200) NOT NULL,
  `numero` VARCHAR(30) NOT NULL,
  `complemento` VARCHAR(30) NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_At` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`tipos` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`especies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`especies` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`especies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`planta_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`planta_status` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`planta_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`plantas` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`plantas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  `especie_id` INT NOT NULL,
  `planta_status_id` INT NOT NULL,
  `descricao` TEXT,
  `foto` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plantas_usuarios_idx` (`usuario_id` ASC),
  INDEX `fk_plantas_tipos1_idx` (`tipo_id` ASC),
  INDEX `fk_plantas_especies1_idx` (`especie_id` ASC),
  INDEX `fk_plantas_planta_status1_idx` (`planta_status_id` ASC),
  CONSTRAINT `fk_plantas_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `troca_verde`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_tipos1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `troca_verde`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_especies1`
    FOREIGN KEY (`especie_id`)
    REFERENCES `troca_verde`.`especies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_planta_status1`
    FOREIGN KEY (`planta_status_id`)
    REFERENCES `troca_verde`.`planta_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`solicitacao_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`solicitacao_status` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`solicitacao_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`solicitacao_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`solicitacao_tipos` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`solicitacao_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`solicitacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`solicitacoes` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`solicitacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `planta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `solicitacao_status_id` INT NOT NULL,
  `solicitacao_tipo_id` INT NOT NULL,
  `finished_at` DATETIME NULL,
  `canceled_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_planta_solicitacoes_plantas1_idx` (`planta_id` ASC),
  INDEX `fk_planta_solicitacoes_usuarios1_idx` (`usuario_id` ASC),
  INDEX `fk_solicitacoes_solicitacoes_status1_idx` (`solicitacao_status_id` ASC),
  INDEX `fk_solicitacoes_solicitacao_tipos1_idx` (`solicitacao_tipo_id` ASC),
  CONSTRAINT `fk_planta_solicitacoes_plantas1`
    FOREIGN KEY (`planta_id`)
    REFERENCES `troca_verde`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planta_solicitacoes_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `troca_verde`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacoes_solicitacoes_status1`
    FOREIGN KEY (`solicitacao_status_id`)
    REFERENCES `troca_verde`.`solicitacao_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacoes_solicitacao_tipos1`
    FOREIGN KEY (`solicitacao_tipo_id`)
    REFERENCES `troca_verde`.`solicitacao_tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`favoritos` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`favoritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `especie_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favoritos_usuarios1_idx` (`usuario_id` ASC),
  INDEX `fk_favoritos_especies1_idx` (`especie_id` ASC),
  CONSTRAINT `fk_favoritos_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `troca_verde`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_especies1`
    FOREIGN KEY (`especie_id`)
    REFERENCES `troca_verde`.`especies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`solicitacao_mensagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`solicitacao_mensagens` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`solicitacao_mensagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitacao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `mensagem` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitacao_mensagens_solicitacoes1_idx` (`solicitacao_id` ASC),
  INDEX `fk_solicitacao_mensagens_usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_solicitacao_mensagens_solicitacoes1`
    FOREIGN KEY (`solicitacao_id`)
    REFERENCES `troca_verde`.`solicitacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_mensagens_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `troca_verde`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `troca_verde`.`solicitacao_transacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `troca_verde`.`solicitacao_transacoes` ;

CREATE TABLE IF NOT EXISTS `troca_verde`.`solicitacao_transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitacao_id` INT NOT NULL,
  `usuario_de_id` INT NOT NULL,
  `usuario_para_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitacao_transacoes_solicitacoes1_idx` (`solicitacao_id` ASC),
  INDEX `fk_solicitacao_transacoes_usuarios1_idx` (`usuario_de_id` ASC),
  INDEX `fk_solicitacao_transacoes_usuarios2_idx` (`usuario_para_id` ASC),
  CONSTRAINT `fk_solicitacao_transacoes_solicitacoes1`
    FOREIGN KEY (`solicitacao_id`)
    REFERENCES `troca_verde`.`solicitacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_transacoes_usuarios1`
    FOREIGN KEY (`usuario_de_id`)
    REFERENCES `troca_verde`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_transacoes_usuarios2`
    FOREIGN KEY (`usuario_para_id`)
    REFERENCES `troca_verde`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
